server:
  port: 8081
spring:
  profiles:
    active: dev
#    active: prod

mybatis-plus:
  # xml
#  mapper-locations: classpath:mapper/*Mapper.xml
  # 实体扫描，多个package用逗号或者分号分隔
  type-aliases-package: com.sfxt.xtts.vo
#  configuration:
  # 这个配置会将执行的sql打印出来，在开发或测试的时候可以用
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

#mybatis:
#debug: true
#  mapper-locations: classpath:mapping/**.xml